package com.mironenko.task2_android.Presenter;

public enum TasksList {
    ADDING_IN_THE_BEGINNING, ADDING_IN_THE_MIDDLE, ADDING_IN_THE_END, SEARCH_BY_VALUE,
    REMOVING_IN_THE_BEGINNING, REMOVING_IN_THE_MIDDLE, REMOVING_IN_THE_END,
    ADDING_NEW, SEARCH_BY_KEY, REMOVING
}
