package com.mironenko.task2_android;

public enum CellViewKeys {
    CELL_ADDING_BEGIN_ARRAY_LIST,
    CELL_ADDING_BEGIN_LINKED_LIST,
    CELL_ADDING_BEGIN_COPY_ON_WRITE_ARRAY_LIST,
    CELL_ADDING_MIDDLE_ARRAY_LIST,
    CELL_ADDING_MIDDLE_LINKED_LIST,
    CELL_ADDING_MIDDLE_COPY_ON_WRITE_ARRAY_LIST,
    CELL_ADDING_END_ARRAY_LIST,
    CELL_ADDING_END_LINKED_LIST,
    CELL_ADDING_END_COPY_ON_WRITE_ARRAY_LIST,

    CELL_SEARCH_BY_VALUE_ARRAY_LIST,
    CELL_SEARCH_BY_VALUE_LINKED_LIST,
    CELL_SEARCH_BY_VALUE_COPY_ON_WRITE_ARRAY_LIST,

    CELL_REMOVING_BEGIN_ARRAY_LIST,
    CELL_REMOVING_BEGIN_LINKED_LIST,
    CELL_REMOVING_BEGIN_COPY_ON_WRITE_ARRAY_LIST,
    CELL_REMOVING_MIDDLE_ARRAY_LIST,
    CELL_REMOVING_MIDDLE_LINKED_LIST,
    CELL_REMOVING_MIDDLE_COPY_ON_WRITE_ARRAY_LIST,
    CELL_REMOVING_END_ARRAY_LIST,
    CELL_REMOVING_END_LINKED_LIST,
    CELL_REMOVING_END_COPY_ON_WRITE_ARRAY_LIST
}
